### ISSUE TITLE
Got error: Cannot assign to read only property 'exports' of object '#<Object>' (mix require and export)

### ISSUE THREAD

**Issue by elverskog** [giladaya/react-fully-scrolled#1]
I got this error, in browser, when trying to run. Cannot assign to read only property 'exports' of object '#<Object>' (mix require and export)

Maybe a webpack version issue? I read `import` and `module.exports` used at the same time is not supported by some versions. In any case I changed to this and it works for me:

var Scroller = require('./Scroller');
var Section = require('./Section');

module.exports = { Scroller: Scroller.default, Section: Section.default };

**Comment by mixalezhnev** [comment]
`import Scroller from './Scroller';
import Section from './Section';

export { Scroller, Section };`
It helped me for create-react-app

**Comment by aka-toxa** [comment]
I've faced same issue, hope you'll fix it guys

**Comment by giladaya** [comment]
Fixed in 2a02fff649aaf1
